### ISSUE TITLE
With docker-compose zipkin tracing not working

### ISSUE THREAD

**Issue by jp1482** [dotnet-architecture/eShopOnDapr#37]
I have used same file as provided. 

1. docker-compose build ( successful)
2. docker-compose up ( sucessful)

It is running fine and display page and call to api working fine. 

Now if I look at localhost:5411. It display zipkin page but no tracing information. 

I have one another application if that application I run using cli -  dapr run then tracing working in that case.

**Comment by jp1482** [comment]
> I have used same file as provided.
> 
> 1. docker-compose build ( successful)
> 2. docker-compose up ( sucessful)
> 
> It is running fine and display page and call to api working fine.
> 
> Now if I look at localhost:5411. It display zipkin page but no tracing information.
> 
> I have one another application if that application I run using cli - dapr run then tracing working in that case.

Issue is resolved. Nothing serious issue and it seems that configuration file has commented code. I have enable that part in eshop-config.yaml. It all started working.

**Comment by fbridger** [comment]
@jp1482 Would you mind sharing how you fixed this problem? I am still experiencing this issue when running the application from Visual Studio

**Comment by paulyuk** [comment]
Hi @fbridger,

I noticed this sample containerizes everything including your apps and dependencies like zipkin.

on my machine I did a `docker ps` and found another zipkin instance here and could see the port forwarding from 5411->9411 in the container:
```bash
a35787df9f4c   openzipkin/zipkin-slim:latest             "start-zipkin"           4 minutes ago   Up About a minute (healthy)   0.0.0.0:5411->9411/tcp              
```

which gave me the hint this is the actual URL we want (just using port 5411 instead of typical 9411):
http://localhost:5411/  <-- this is the fix/answer :)

per @devenliu also just make sure that `/dapr/configuration/eshop-config.yaml` has the last two zipkin lines.  When I pulled from main it was right.

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: config
  namespace: eshop
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin:9411/api/v2/spans"
```
